# Generated by Django 5.0.6 on 2024-07-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('oferta', models.IntegerField()),
                ('precio_anterior', models.IntegerField(blank=True, null=True)),
                ('multiple', models.IntegerField()),
                ('tipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='tienda.tipoproducto')),
            ],
        ),
    ]
