# Generated by Django 5.0.6 on 2024-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='multiple',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_anterior',
        ),
        migrations.AddField(
            model_name='producto',
            name='multiples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='ofertas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
