# Generated by Django 5.0.6 on 2024-07-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_multiple_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariacionProducto',
            fields=[
                ('id', models.AutoField(db_column='idVariacion', primary_key=True, serialize=False)),
                ('nombreVariacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='multiples',
        ),
        migrations.AddField(
            model_name='producto',
            name='idVariacion',
            field=models.ForeignKey(db_column='idVariacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.variacionproducto'),
        ),
    ]
