# Generated by Django 5.0.6 on 2024-07-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_variacionproducto_remove_producto_multiples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ofertas',
        ),
    ]
