# Generated by Django 5.0.6 on 2024-07-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_stock_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idVariacion',
            field=models.ForeignKey(blank=True, db_column='idVariacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.variacionproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='variacionproducto',
            name='nombreVariacion',
            field=models.CharField(max_length=200),
        ),
    ]
